### ISSUE TITLE
Weird compat-related crash

### ISSUE THREAD

**Issue by Sunconure11** [FirstMegaGame4/Fabric-Anvils#3]
https://github.com/williambl/haema/issues/125

**Comment by FirstMegaGame4** [comment]
Wait what!? My ***anvil*** mod has a compatibility issue with a mod that adds ***rats***!?

**Comment by Sunconure11** [comment]
Compat issue seems to have been dealt with. It was a mixin error with Haema.

**Comment by Sunconure11** [comment]
Though I'm still hunting down other errors.

**Comment by FirstMegaGame4** [comment]
I can close this issue ?

**Comment by Sunconure11** [comment]
Let me check everything first, then I'll tell you. There is an unrelated mod I'm trying to see why it is erroring.

**Comment by FirstMegaGame4** [comment]
Okay

**Comment by Sunconure11** [comment]
Yeah you can probably close this now

**Comment by Sunconure11** [comment]
I'll use this issue if the issue is still present with a recent bugfix

**Comment by Sunconure11** [comment]
[crash-2022-04-27_10.45.23-client.txt](https://github.com/FirstMegaGame4/Fabric-Anvils/files/8573159/crash-2022-04-27_10.45.23-client.txt)
[crash-2022-04-27_10.45.18-server.txt](https://github.com/FirstMegaGame4/Fabric-Anvils/files/8573160/crash-2022-04-27_10.45.18-server.txt)

**Comment by Sunconure11** [comment]
You might want to go over your mixins, turning off your mod stops these weird errors

**Comment by FirstMegaGame4** [comment]
I think my mod is incompatible with alloy forgery, as soon as i have time i will try to fix it

**Comment by FirstMegaGame4** [comment]
I can't find any potential mixin compatibility issues with Alloy Forgery, wouldn't it just be Alloy Forgery causing this issue?

**Comment by fzzyhmstrs** [comment]
@Sunconure11 you had opened an issue on my mod issue tracker also, and after a bit of poking I believe that the issue might be coming from the mod *Anvil fix* (AnvilFix 1.3.0). *Anvil fix* also modifies the anvil level limit constant, so fabric-anvils mixin fails when it can't find the original level limit constant to modify (again). I would try taking *Anvil fix* out and seeing if that fixes it. *Fabric anvils* has the same functionality anyways.

In my own test environment, I get a crash with *alloy forgery*, *fabric anvils*, and *anvil fix* all included, but no crash with only *fabric anvils* and *alloy forgery*
